name: realm_generator
description: Generates RealmObject classes from Realm data model classes. This package is part of the official Realm Flutter and Realm Dart SDKs 
version: 0.1.0+preview

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart 
issue_tracker: https://github.com/realm/realm-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.3.0
  build_resolvers: ^2.0.0
  build_runner: ^2.1.2
  build: ^2.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.0
  json_annotation: ^4.3.0
  source_gen: ^1.1.1

dev_dependencies:
  build_version: ^2.1.0
  json_serializable: ^6.0.0
