targets:
    $default:
        builders:
            realm_generator|realm_object_builder:
                enabled: true
                generate_for:
                    - example/**.dart
                    - test/**.dart
                    - lib/main.dart