name: Realm Dart for Linux

on:
  push:
    branches: [ master ]
    # Do not run if change is in these paths
    paths-ignore:
      - 'flutter/**'
      - 'generator/**'
  pull_request:
    # Do not run if change is in these paths
    paths-ignore:
        - 'flutter/**'
        - 'generator/**'

jobs:
  CI:
    runs-on: ubuntu-20.04
    env:
      REALM_CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build Realm Dart for Linux
        run: ./scripts/build-linux.sh

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - name : Setup Dart SDK
        uses: dart-lang/setup-dart@main

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test --reporter expanded --coverage coverage/

      - name: Generate coverage report
        run: |
          dart run coverage:format_coverage \
            --in coverage/ \
            --out coverage/lcov.info \
            --check-ignore \
            --lcov \
            --packages .packages \
            --report-on lib

      - name: Publish Coverage
        id: publish-coverage
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: generator

      - name: Output Coveralls response
        run: echo ${{ steps.publish-coverage.outputs.coveralls-api-result }}

      - name: Run generator tests
        run: |
          pushd generator
          dart test --reporter expanded --coverage coverage/
          popd

      - name: Generate generator coverage report
        run: |
          pushd generator
          dart run coverage:format_coverage \
            --in coverage/ \
            --out coverage/lcov.info \
            --check-ignore \
            --lcov \
            --packages .packages \
            --report-on lib
          popd

      - name: Publish Generator Coverage
        id: publish-generator-coverage
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: realm_generator
          path-to-lcov: ./generator/coverage/lcov.info

      - name: Output Coveralls response
        run: echo ${{ steps.publish-generator-coverage.outputs.coveralls-api-result }}
    
