name: metrics
description: 
  Command-line application for gathering build time metrics for realm-dart usage. 
  Also used as a library in realm_generator builder.
version: 0.2.0-alpha

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  json_annotation: ^4.3.0
  crypto: ^3.0.0

dev_dependencies:
  build_cli: ^2.1.3
  build_runner: ^2.1.4
  build_version: ^2.1.0
  dependency_validator: ^3.1.0
  json_serializable: ^6.0.0
  lints: ^1.0.1
  
